import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { TooltipProvider } from '@/src/ui/ui-tooltip/tooltip';
import TabBarClient from '@/widgets/tab-bar-client/tab-bar-client';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <TooltipProvider>
          <header className="w-full px-4 border-b border-border bg-card">
            <TabBarClient />
          </header>

          <main className="flex-1 w-full p-4">{children}</main>
        </TooltipProvider>
      </body>
    </html>
  );
}
