import {
  BarChart3,
  Calculator,
  CircleHelp,
  Landmark,
  LayoutDashboard,
  ListChecks,
  Mail,
  Package,
  Phone,
  Settings,
  ShoppingBag,
  ShoppingCart,
} from 'lucide-react';
import { TabBarItem } from '@/entities/tab-bar/tab-bar-item';

export const TabsData: TabBarItem[] = [
  {
    id: '1',
    title: 'Dashboard',
    url: '/dashboard',
    isPinned: false,
    isActive: true,
    icon: <LayoutDashboard />,
  },
  {
    id: '2',
    title: 'Banking',
    url: '/banking',
    isPinned: false,
    isActive: false,
    icon: <Landmark />,
  },
  {
    id: '3',
    title: 'Telefonie',
    url: '/telefonie',
    isPinned: false,
    isActive: false,
    icon: <Phone />,
  },
  {
    id: '4',
    title: 'Accounting',
    url: '/accounting',
    isPinned: false,
    isActive: false,
    icon: <Calculator />,
  },
  {
    id: '5',
    title: 'Verkauf',
    url: '/verkauf',
    isPinned: false,
    isActive: false,
    icon: <ShoppingCart />,
  },
  {
    id: '6',
    title: 'Statistik',
    url: '/statistik',
    isPinned: false,
    isActive: false,
    icon: <BarChart3 />,
  },
  {
    id: '7',
    title: 'Post Office',
    url: '/post-office',
    isPinned: false,
    isActive: false,
    icon: <Mail />,
  },
  {
    id: '8',
    title: 'Administration',
    url: '/administration',
    isPinned: false,
    isActive: false,
    icon: <Settings />,
  },
  {
    id: '9',
    title: 'Help',
    url: '/help',
    isPinned: false,
    isActive: false,
    icon: <CircleHelp />,
  },
  {
    id: '10',
    title: 'Warenbestand',
    url: '/warenbestand',
    isPinned: false,
    isActive: false,
    icon: <Package />,
  },
  {
    id: '11',
    title: 'Auswahllisten',
    url: '/auswahllisten',
    isPinned: false,
    isActive: false,
    icon: <ListChecks />,
  },
  {
    id: '12',
    title: 'Einkauf',
    url: '/einkauf',
    isPinned: false,
    isActive: false,
    icon: <ShoppingBag />,
  },
];
